# DISKRITISASI

diskritasi adalah kegiatan yang dilakukan untuk mengubah nila data numerik menjadi kategorial. iscretization atau binning digunakan untuk mengubah atribut numerik menjadi atribut kategorikal. Perubahan tersebut dilakukan dengan mengkategorikan atribut numerik menjadi beberapa tingkatan atribut kategorikal. Sebagai contoh, apabila terdapat data numerik dengan data berikut:

$$ 2, 4, 10, 17, 5, 23, 11, 48, 35, 56, 20$$

Maka, dengan discretization, data tersebut dapat dikategorikan menjadi dua kelompok:

$$Kelompok\ 1 (Dibawah\ 25): 2, 4, 5,10, 11, 17, 20, 23$$

$$Kelompok\ 2 (Diatas\ 25): 35, 48, 56$$

Mengubah data numerik menjadi kategorikal memungkinkan data tersebut untuk dianalisis dengan menggunakan analisis kategorikal. Sehingga, informasi baru bisa didapatkan dari data tersebut.

In [82]:
#Datasets iris
import pandas as pd
import numpy as np
from math import log2
import statistics as st
pd.options.mode.chained_assignment=None

url='https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
data=pd.read_csv(url)
data

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

1. Equal Width Intervals

equal width adalah algoritma untuk membagi rentang dari X menjadi K interval dengan ukuran lebar yang sama

**Method cut digunakan untuk mencari interval menggunakan metode equal-width interval*

In [83]:
# KolomData
panjang_sepal = data["sepal.length"]
lebar_sepal = data["sepal.width"]
panjang_petal = data["petal.length"]
lebar_petal = data["petal.width"]

*Proses diskritisasi dengan equal width dan equal frequency*

**Equal Width Intervals**

adalah discretization yang membagi data numerik menjadi beberapa kelompok dengan lebar kelompok yang kurang lebih sama besar.

*Cut adalah sebuah method pada library pandas untuk melakukan perhitungan equal width frequency intervals*

Syntax

pd.cut(series, interval, right=True, label)

**Sepal Width**


Equal Width Intervals lebar kelopak bunga Iris dikelomokkan menjadi 3 kategori yaitu sedikit lebar, lebar, sangat lebar

In [84]:
# interval equal-width
# ew = equal-width

# label kategori
# label kategori
label = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
# Untuk menghitung banyaknya kategori label
jumlah_kategori = len(label)

# untuk menghitung interval equal-width
data_lebarsepal_ew = pd.cut(lebar_sepal, jumlah_kategori, True, label)
jumlahdata_kategori_lebarsepal_ew = data_lebarsepal_ew.value_counts()
jumlahdata_interval_lebarsepal_ew = pd.cut(lebar_sepal, jumlah_kategori, True).value_counts()

In [85]:
# dataframe dari sepal.widht beserta kategorinya, concat untuk menggabungkan beberapa kolom
df_lebarsepal_ew=pd.DataFrame(pd.concat((lebar_sepal, data_lebarsepal_ew), axis = 1))

In [86]:
df_lebarsepal_ew.columns = ["sepal.width", "category"]
df_lebarsepal_ew

     sepal.width       category
0            3.5          Lebar
1            3.0          Lebar
2            3.2          Lebar
3            3.1          Lebar
4            3.6          Lebar
..           ...            ...
145          3.0          Lebar
146          2.5  Sedikit Lebar
147          3.0          Lebar
148          3.4          Lebar
149          3.0          Lebar

[150 rows x 2 columns]

*jumlah data sepal width berdasarkan kategori*

In [87]:
jumlahdata_kategori_lebarsepal_ew

Lebar            88
Sedikit Lebar    47
Sangat Lebar     15
Name: sepal.width, dtype: int64

*jumlah data sepal width berdasarkan interval*

In [88]:
jumlahdata_interval_lebarsepal_ew

(2.8, 3.6]      88
(1.998, 2.8]    47
(3.6, 4.4]      15
Name: sepal.width, dtype: int64

**Sepal Length**

Equal Width Intervals panjang kelopak bunga Iris dikelompokkan menjadi 3 kategori yaitu sedikit lebar ,lebar,
sangat lebar

In [89]:
# interval equal-width
# ew = equal-width

# label kategori
label = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
# Untuk menghitung banyaknya kategori label
jumlah_kategori = len(label)

# untuk menghitung interval equal-width
data_panjangsepal_ew = pd.cut(panjang_sepal, jumlah_kategori, True, label)
jumlahdata_kategori_panjangsepal_ew = data_panjangsepal_ew.value_counts()
jumlahdata_interval_panjangsepal_ew = pd.cut(panjang_sepal, jumlah_kategori, True).value_counts()

In [90]:
# dataframe dari sepal.length beserta kategorinya , concat untuk menggabungkan beberapa kolom
df_panjangsepal_ew=pd.DataFrame(pd.concat((panjang_sepal, data_panjangsepal_ew), axis = 1))

In [91]:
df_panjangsepal_ew.columns = ["sepal.width", "category"]
df_panjangsepal_ew

     sepal.width       category
0            5.1  Sedikit Lebar
1            4.9  Sedikit Lebar
2            4.7  Sedikit Lebar
3            4.6  Sedikit Lebar
4            5.0  Sedikit Lebar
..           ...            ...
145          6.7          Lebar
146          6.3          Lebar
147          6.5          Lebar
148          6.2          Lebar
149          5.9          Lebar

[150 rows x 2 columns]

*#jumlah data sepal length berdasarkan kategori*

In [92]:
jumlahdata_kategori_panjangsepal_ew

Lebar            71
Sedikit Lebar    59
Sangat Lebar     20
Name: sepal.length, dtype: int64

*jumlah data sepal.length berdasarkan interval*

In [93]:
jumlahdata_interval_panjangsepal_ew

(5.5, 6.7]      71
(4.296, 5.5]    59
(6.7, 7.9]      20
Name: sepal.length, dtype: int64

**petal width** 

berdasarkan lebar mahkota bunga iris dikelompokkan menjadi 3:

sedikit lebar,lebar
,sangat lebar

In [94]:
# interval equal-width
# ew = equal-width

# label kategori
label = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
# Untuk menghitung banyaknya kategori label
jumlah_kategori = len(label)

# untuk menghitung interval equal-width
data_lebarpetal_ew = pd.cut(lebar_petal, jumlah_kategori, True, label)
jumlahdata_kategori_lebarpetal_ew = data_lebarpetal_ew.value_counts()
jumlahdata_interval_lebarpetal_ew = pd.cut(lebar_petal, jumlah_kategori, True).value_counts()

In [95]:
# dataframe dari petal.widht beserta kategorinya
# concat untuk menggabungkan beberapa kolom
df_lebarpetal_ew=pd.DataFrame(pd.concat((lebar_petal, data_lebarpetal_ew), axis = 1))

In [96]:
df_lebarpetal_ew.columns = ["petal.width", "category"]
df_lebarpetal_ew

     petal.width       category
0            0.2  Sedikit Lebar
1            0.2  Sedikit Lebar
2            0.2  Sedikit Lebar
3            0.2  Sedikit Lebar
4            0.2  Sedikit Lebar
..           ...            ...
145          2.3   Sangat Lebar
146          1.9   Sangat Lebar
147          2.0   Sangat Lebar
148          2.3   Sangat Lebar
149          1.8   Sangat Lebar

[150 rows x 2 columns]

In [97]:
#jumlah data petal.width berdasarkan kategori
jumlahdata_kategori_lebarpetal_ew

Lebar            54
Sedikit Lebar    50
Sangat Lebar     46
Name: petal.width, dtype: int64

In [98]:
#jumlah data petal.width berdasarkan interval
jumlahdata_interval_lebarpetal_ew

(0.9, 1.7]       54
(0.0976, 0.9]    50
(1.7, 2.5]       46
Name: petal.width, dtype: int64

**Petal Length**

Equal Width Intervals panjang mahkota bunga Iris dikelompokkan menjadi 3 kategori yaitu sedikit lebar ,lebar, sangat lebar

In [99]:
# interval equal-width
# ew = equal-width

# label kategori
label = ["Sedikit Lebar", "Lebar", "Sangat lebar"]
# Untuk menghitung banyaknya kategori label
jumlah_kategori = len(label)

# untuk menghitung interval equal-width
data_panjangpetal_ew = pd.cut(panjang_petal, jumlah_kategori, True, label)
jumlahdata_kategori_panjangpetal_ew = data_panjangpetal_ew.value_counts()
jumlahdata_interval_panjangpetal_ew = pd.cut(panjang_petal, jumlah_kategori, True).value_counts()

In [100]:
# dataframe dari petal.length beserta kategorinya, concat untuk menggabungkan beberapa kolom
df_panjangpetal_ew=pd.DataFrame(pd.concat((panjang_petal, data_panjangpetal_ew), axis = 1))

In [101]:
df_panjangpetal_ew.columns = ["petal.width", "category"]
df_panjangpetal_ew

     petal.width       category
0            1.4  Sedikit Lebar
1            1.4  Sedikit Lebar
2            1.3  Sedikit Lebar
3            1.5  Sedikit Lebar
4            1.4  Sedikit Lebar
..           ...            ...
145          5.2   Sangat lebar
146          5.0   Sangat lebar
147          5.2   Sangat lebar
148          5.4   Sangat lebar
149          5.1   Sangat lebar

[150 rows x 2 columns]

*#jumlah data petal length berdasarkan kategori*

In [102]:
jumlahdata_kategori_panjangpetal_ew

Lebar            54
Sedikit Lebar    50
Sangat lebar     46
Name: petal.length, dtype: int64

*jumlah data petal.length berdasarkan interval*

In [103]:
jumlahdata_interval_panjangpetal_ew

(2.967, 4.933]    54
(0.994, 2.967]    50
(4.933, 6.9]      46
Name: petal.length, dtype: int64

In [104]:
panjang_sepal["Kategori"] = pd.cut(data["sepal.length"],3, labels = ['sedikit lebar','lebar','sangat lebar'])
lebar_sepal["Kategori"] = pd.cut(data["sepal.width"],3, labels = ['sedikit lebar','lebar','sangat lebar'])
panjang_petal['Kategori'] = pd.cut(data["petal.length"],3, labels = ['sedikit lebar','lebar','sangat lebar'])
lebar_petal['Kategori'] = pd.cut(data["petal.width"],3, labels = ['sedikit lebar','lebar','sangat lebar'])

equalWidth = pd.DataFrame([])
equalWidth["sepal.length"] = data["sepal.length"]
equalWidth['sepal_length_category'] = panjang_sepal["Kategori"]

equalWidth["sepal.width"] = data["sepal.width"]
equalWidth["sepal_width_category"] = lebar_sepal["Kategori"]

equalWidth["petal.length"] = data["petal.length"]
equalWidth["petal_length_category"] = panjang_petal["Kategori"]

equalWidth["petal.width"] = data["petal.width"]
equalWidth["petal_width_category"] = lebar_petal["Kategori"]

equalWidth["variety"] = data[["variety"]]

equalWidth

,sepal.length,sepal_length_category,sepal.width,sepal_width_category,petal.length,petal_length_category,petal.width,petal_width_category,variety
0,5.1,sedikit lebar,3.5,lebar,1.4,sedikit lebar,0.2,sedikit lebar,Setosa
1,4.9,sedikit lebar,3.0,lebar,1.4,sedikit lebar,0.2,sedikit lebar,Setosa
2,4.7,sedikit lebar,3.2,lebar,1.3,sedikit lebar,0.2,sedikit lebar,Setosa
3,4.6,sedikit lebar,3.1,lebar,1.5,sedikit lebar,0.2,sedikit lebar,Setosa
4,5.0,sedikit lebar,3.6,lebar,1.4,sedikit lebar,0.2,sedikit lebar,Setosa
...,...,...,...,...,...,...,...,...,...
145,6.7,lebar,3.0,lebar,5.2,sangat lebar,2.3,sangat lebar,Virginica
146,6.3,lebar,2.5,sedikit lebar,5.0,sangat lebar,1.9,sangat lebar,Virginica
147,6.5,lebar,3.0,lebar,5.2,sangat lebar,2.0,sangat lebar,Virginica
148,6.2,lebar,3.4,lebar,5.4,sangat lebar,2.3,sangat lebar,Virginica
149,5.9,lebar,3.0,lebar,5.1,sangat lebar,1.8,sangat lebar,Virginica

**Equal Frequency Intervals**

adalah discretization yang membagi data numerik menjadi beberapa kelompok dengan jumlah anggota yang kurang lebih sama besar.

*Qcut adalah sebuah method pada library pandas untuk melakukan perhitungan equal frequency intervals*

pandas menyediakan qcut untuk mencari nilai interval dari Equal-Frequency Intervals

Syntax
pd.qcut(series, interval, label)

Sepal Width

Equal Frequency Intervals lebar kelopak bunga Iris dikelompokkan menjadi 3 kategori yaitu sedikit lebar
,sangat lebar

In [105]:
# KolomData
panjang_sepal = data["sepal.length"]
lebar_sepal = data["sepal.width"]
panjang_petal = data["petal.length"]
lebar_petal = data["petal.width"]

In [106]:
# interval equal-frequency
# ef = equal-frequency

# label kategori
label = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
# Untuk menghitung banyaknya kategori label
jumlah_kategori = len(label)

# untuk menghitung interval equal-frequency
data_lebarsepal_ef = pd.qcut(lebar_sepal, jumlah_kategori, label)
jumlahdata_kategori_lebarsepal_ef = data_lebarsepal_ef.value_counts()
jumlahdata_interval_lebarsepal_ef = pd.qcut(lebar_sepal, jumlah_kategori).value_counts()

In [107]:
# dataframe dari sepal.widht beserta kategorinya
# concat untuk menggabungkan beberapa kolom
df_lebarsepal_ef=pd.DataFrame(pd.concat((lebar_sepal, data_lebarsepal_ef), axis = 1))

In [108]:
df_lebarsepal_ef.columns = ["sepal.width", "category"]
df_lebarsepal_ef

     sepal.width       category
0            3.5   Sangat Lebar
1            3.0          Lebar
2            3.2          Lebar
3            3.1          Lebar
4            3.6   Sangat Lebar
..           ...            ...
145          3.0          Lebar
146          2.5  Sedikit Lebar
147          3.0          Lebar
148          3.4   Sangat Lebar
149          3.0          Lebar

[150 rows x 2 columns]

*jumlah data sepal.width berdasarkan kategori*

In [109]:
jumlahdata_kategori_lebarsepal_ef

Sedikit Lebar    57
Lebar            50
Sangat Lebar     43
Name: sepal.width, dtype: int64

*jumlah data sepal.width berdasarkan interval*

In [110]:
jumlahdata_interval_lebarsepal_ef

(1.999, 2.9]    57
(2.9, 3.2]      50
(3.2, 4.4]      43
Name: sepal.width, dtype: int64

**Petal Width**

* Equal Width Intervals lebar mahkota bunga Iris dikelompokkan menjadi 3 kategori yaitu sedikit lebar, lebar,sangat lebar

In [111]:
# interval equal-frequency
# ef = equal-frequency

# label kategori
label = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
# Untuk menghitung banyaknya kategori label
jumlah_kategori = len(label)

# untuk menghitung interval equal-frequency
data_lebarpetal_ef = pd.qcut(lebar_petal, jumlah_kategori, label)
jumlahdata_kategori_lebarpetal_ef = data_lebarpetal_ef.value_counts()
jumlahdata_interval_lebarpetal_ef = pd.qcut(lebar_petal, jumlah_kategori).value_counts()

In [112]:
# dataframe dari petal.widht beserta kategorinya
# concat untuk menggabungkan beberapa kolom
df_lebarpetal_ef=pd.DataFrame(pd.concat((lebar_petal, data_lebarpetal_ef), axis = 1))

In [113]:
df_lebarpetal_ef.columns = ["petal.width", "category"]
df_lebarpetal_ef

     petal.width       category
0            0.2  Sedikit Lebar
1            0.2  Sedikit Lebar
2            0.2  Sedikit Lebar
3            0.2  Sedikit Lebar
4            0.2  Sedikit Lebar
..           ...            ...
145          2.3   Sangat Lebar
146          1.9   Sangat Lebar
147          2.0   Sangat Lebar
148          2.3   Sangat Lebar
149          1.8   Sangat Lebar

[150 rows x 2 columns]

*#jumlah data petal.width berdasarkan kategori*

In [114]:
jumlahdata_kategori_lebarpetal_ef

Lebar            52
Sedikit Lebar    50
Sangat Lebar     48
Name: petal.width, dtype: int64

*#jumlah data petal.width berdasarkan interval*

In [115]:
jumlahdata_interval_lebarpetal_ef

(0.867, 1.6]      52
(0.099, 0.867]    50
(1.6, 2.5]        48
Name: petal.width, dtype: int64

**Sepal Length**

Equal Frequency Intervals panjang kelopak bunga Iris dikelompokkan menjadi 3 kategori yaitu sedikit lebar, lebar,
sangat lebar

In [116]:
# interval equal-frequency
# ef = equal-frequency

# label kategori
label = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
# Untuk menghitung banyaknya kategori label
jumlah_kategori = len(label)

# untuk menghitung interval equal-frequency
data_panjangsepal_ef = pd.qcut(panjang_sepal, jumlah_kategori, label)
jumlahdata_kategori_panjangsepal_ef = data_panjangsepal_ef.value_counts()
jumlahdata_interval_panjangsepal_ef = pd.qcut(panjang_sepal, jumlah_kategori).value_counts()

In [117]:
# dataframe dari sepal.length beserta kategorinya
# concat untuk menggabungkan beberapa kolom
df_panjangsepal_ef=pd.DataFrame(pd.concat((panjang_sepal, data_panjangsepal_ef), axis = 1))

In [118]:
df_panjangsepal_ef.columns = ["sepal.width", "category"]
df_panjangsepal_ef

     sepal.width       category
0            5.1  Sedikit Lebar
1            4.9  Sedikit Lebar
2            4.7  Sedikit Lebar
3            4.6  Sedikit Lebar
4            5.0  Sedikit Lebar
..           ...            ...
145          6.7   Sangat Lebar
146          6.3          Lebar
147          6.5   Sangat Lebar
148          6.2          Lebar
149          5.9          Lebar

[150 rows x 2 columns]

*jumlah data sepal.length berdasarkan kategori*

In [119]:
jumlahdata_kategori_panjangsepal_ef

Lebar            56
Sedikit Lebar    52
Sangat Lebar     42
Name: sepal.length, dtype: int64

*jumlah data sepal.length berdasarkan interval*

In [120]:
jumlahdata_interval_panjangsepal_ef

(5.4, 6.3]                   56
(4.2989999999999995, 5.4]    52
(6.3, 7.9]                   42
Name: sepal.length, dtype: int64

Petal Length

Equal Frequency Intervals panjang mahkota bunga Iris dikelompokkan menjadi 3 kategori yaitu sedikit lebar, lebar,
sangat lebar

In [121]:
# interval equal-frequency
# ef = equal-frequency

# label kategori
label = ["Sedikit Lebar", "Lebar", "Sangat Lebar"]
# Untuk menghitung banyaknya kategori label
jumlah_kategori = len(label)

# untuk menghitung interval equal-frequency
data_panjangpetal_ef = pd.qcut(panjang_petal, jumlah_kategori, label)
jumlahdata_kategori_panjangpetal_ef = data_panjangpetal_ef.value_counts()
jumlahdata_interval_panjangpetal_ef = pd.qcut(panjang_petal, jumlah_kategori).value_counts()

In [122]:
# dataframe dari petal.length beserta kategorinya
# concat untuk menggabungkan beberapa kolom
df_panjangpetal_ef=pd.DataFrame(pd.concat((panjang_petal, data_panjangpetal_ef), axis = 1))

In [123]:
df_panjangpetal_ef.columns = ["petal.width", "category"]
df_panjangpetal_ef

     petal.width       category
0            1.4  Sedikit Lebar
1            1.4  Sedikit Lebar
2            1.3  Sedikit Lebar
3            1.5  Sedikit Lebar
4            1.4  Sedikit Lebar
..           ...            ...
145          5.2   Sangat Lebar
146          5.0   Sangat Lebar
147          5.2   Sangat Lebar
148          5.4   Sangat Lebar
149          5.1   Sangat Lebar

[150 rows x 2 columns]

In [124]:
#jumlah data petal.length berdasarkan kategori
jumlahdata_kategori_lebarpetal_ef

Lebar            52
Sedikit Lebar    50
Sangat Lebar     48
Name: petal.width, dtype: int64

In [125]:
#jumlah data petal.length berdasarkan interval
jumlahdata_interval_lebarpetal_ef

(0.867, 1.6]      52
(0.099, 0.867]    50
(1.6, 2.5]        48
Name: petal.width, dtype: int64

In [126]:
panjang_sepal["Kategori"] = pd.qcut(data["sepal.length"],3, labels = ['sedikit lebar','lebar','sangat lebar'])
lebar_sepal["Kategori"] = pd.qcut(data["sepal.width"],3, labels = ['sedikit lebar','lebar','sangat lebar'])
panjang_petal['Kategori'] = pd.qcut(data["petal.length"],3, labels = ['sedikit lebar','lebar','sangat lebar'])
lebar_petal['Kategori'] = pd.qcut(data["petal.width"],3, labels = ['sedikit lebar','lebar','sangat lebar'])

equalFrequency = pd.DataFrame([])
equalFrequency["sepal.length"] = data["sepal.length"]
equalFrequency['sepal_length_category'] = panjang_sepal["Kategori"]

equalFrequency["sepal.width"] = data["sepal.width"]
equalFrequency["sepal_width_category"] = lebar_sepal["Kategori"]

equalFrequency["petal.length"] = data["petal.length"]
equalFrequency["petal_length_category"] = panjang_petal["Kategori"]

equalFrequency["petal.width"] = data["petal.width"]
equalFrequency["petal_width_category"] = lebar_petal["Kategori"]

equalFrequency["variety"] = data[["variety"]]

equalFrequency

,sepal.length,sepal_length_category,sepal.width,sepal_width_category,petal.length,petal_length_category,petal.width,petal_width_category,variety
0,5.1,sedikit lebar,3.5,sangat lebar,1.4,sedikit lebar,0.2,sedikit lebar,Setosa
1,4.9,sedikit lebar,3.0,lebar,1.4,sedikit lebar,0.2,sedikit lebar,Setosa
2,4.7,sedikit lebar,3.2,lebar,1.3,sedikit lebar,0.2,sedikit lebar,Setosa
3,4.6,sedikit lebar,3.1,lebar,1.5,sedikit lebar,0.2,sedikit lebar,Setosa
4,5.0,sedikit lebar,3.6,sangat lebar,1.4,sedikit lebar,0.2,sedikit lebar,Setosa
...,...,...,...,...,...,...,...,...,...
145,6.7,sangat lebar,3.0,lebar,5.2,sangat lebar,2.3,sangat lebar,Virginica
146,6.3,lebar,2.5,sedikit lebar,5.0,sangat lebar,1.9,sangat lebar,Virginica
147,6.5,sangat lebar,3.0,lebar,5.2,sangat lebar,2.0,sangat lebar,Virginica
148,6.2,lebar,3.4,sangat lebar,5.4,sangat lebar,2.3,sangat lebar,Virginica
149,5.9,lebar,3.0,lebar,5.1,sangat lebar,1.8,sangat lebar,Virginica

Entropy

Entropi merupakan distribusi probabilitas dalam teori informasi dan diadopsi kedalam Algoritme C4.5 untuk mengukur tingkat homogenitas distribusi kelas dari sebuah himpunan data (dataset). Sebagai ilustrasi, semakin tinggi tingkat entropi dari sebuah dataset maka semakin homogen distribusi kelas pada dataset tersebut. Persamaan untuk menghitung entropi pada pohon keputusan C4.5 ditunjukan pada Persamaan 1 (Raditya, 2009):


$$
\begin{align*}
\displaystyle Entropy(S) &= \sum_{i=0}^{k} -phi \ log_{2} \ phi \\
Keterangan &: \\
S &= Himpunan \ dataset  \\
k &= Banyaknya \ partisi \ S \\
phi &= Proporsi \ S_{i} \ terhadap \ S
\end{align*}
$$

Persiapan

* Impor modul log2 dari *package math*
* Ambil data yang akan digunakan

In [127]:
# Dataframe yang akan digunakan
target_data = df_lebarpetal_ef
target_data

     petal.width       category
0            0.2  Sedikit Lebar
1            0.2  Sedikit Lebar
2            0.2  Sedikit Lebar
3            0.2  Sedikit Lebar
4            0.2  Sedikit Lebar
..           ...            ...
145          2.3   Sangat Lebar
146          1.9   Sangat Lebar
147          2.0   Sangat Lebar
148          2.3   Sangat Lebar
149          1.8   Sangat Lebar

[150 rows x 2 columns]

In [128]:
# Label Kategori
labels = ['Sedikit Lebar', 'Lebar', 'Sangat Lebar']

In [129]:
#fungsi yang digunakan untuk menghitung banyaknya data berdasarkan kategori
def hitung_setiap_kategori(kolom_data, labels, kolom, kategori):
  grup = kolom_data.groupby(kategori).count()
  jumlah_setiap_kategori = []
  for label in labels:
    jumlah_setiap_kategori.append(grup.loc[label, kolom])
  return jumlah_setiap_kategori

In [130]:
hitung_setiap_kategori(target_data, labels, target_data.columns[0], target_data.columns[1])

[50, 52, 48]

In [131]:
#fungsi yang digunakan untuk proses info D
def split(nilai,kolom_data, labels, kolom, kategori):
  less_group =kolom_data[kolom_data[kolom] < nilai]
  greater_group =kolom_data[kolom_data[kolom] >= nilai]

  length_less_group = hitung_setiap_kategori(less_group, labels, kolom, kategori)
  length_greater_group = hitung_setiap_kategori(greater_group, labels, kolom, kategori)

  return (length_less_group, length_greater_group)

In [132]:
#fungsi untuk menghitung nilai entropy
def entropy(target_data):
    all_prob = []
    for prob in target_data:
        if (prob/sum(target_data) != 0):
            all_prob.append(prob/sum(target_data) * log2(prob/sum(target_data)))
        else:
            all_prob.append(0)
    return -(sum(all_prob))

$$ Info_A(D) = \frac{|D_1|}{|D|} Entropy (D_1)\frac{|D_2|}{|D|}+ Entropy (D_2)$$

In [133]:
# fungsi untuk menghitung nilai info
def info(d, target_data):
    temp = []
    for value in d:
        temp.append((sum(value) / target_data.shape[0]) * entropy(value))
    return sum(temp)

In [134]:
# fungsi untuk menghitung nilai gain
def gain(inisial, new):
  return inisial - new

In [135]:
d = hitung_setiap_kategori(target_data, labels, target_data.columns[0], target_data.columns[1])
Einisial = entropy(d)
Einisial

1.5841928580512907

**Gain**

Setelah membagi dataset berdasarkan sebuah atribut kedalam subset yang lebih kecil, entropi dari data tersebut akan berubah. Perubahan entropi ini dapat digunakan untuk menentukan bagus tidaknya pembagian data yang telah dilakukan. Perubahan entropi ini disebut dengan information gain dalam Algoritme C4.5. Information gain ini diukur dengan menghitung selisih antara entropi dataset sebelum dan sesudah pembagian (splitting) dilakukan. Pembagian yang terbaik
akan menghasilkan entropi subset yang paling kecil, dengan demikian berdampak pada information gain yang terbesar. Persamaan untuk menghitung nilai Gain pada pohon keputusan ditujukan pada Persamaan 2 (Raditya, 2009):
</p>

$$
\begin{align*}
\displaystyle 𝐺𝑎𝑖𝑛(𝐴) &= 𝐸𝑛𝑡𝑟𝑜𝑝𝑖(𝑆) − \sum_{i=1}^{k}\frac{\left| S \right|}{\left| S_{i} \right|} * 𝐸𝑛𝑡𝑟𝑜𝑝𝑖(𝑆_{i}) \\
Keterangan &: \\
𝑆 &: himpunan \ kasus \\
𝐴 &: atribut \\
k &: jumlah \ partisi \ atribut \ A \\
|𝑆𝑖| &: jumlah \ kasus \ pada \ partisi \ ke-i \\
|𝑆| &: jumlah \ kasus \ dalam \ S 
\end{align*}
$$

In [136]:
# Untuk mencari split 0.7
az = split(0.7, target_data, labels, target_data.columns[0], target_data.columns[1])
Enew1 = info(az, target_data)
gain(Einisial, Enew1)

0.9182958340544896

In [137]:
# Untuk mencari split 1.4
az = split(1.4, target_data, labels, target_data.columns[0], target_data.columns[1])
Enew2 = info(az, target_data)
gain(Einisial, Enew2)

0.6536600192724277

In [138]:
# Untuk mencari split 2.1
az = split(2.1, target_data, labels, target_data.columns[0], target_data.columns[1])
Enew3 = info(az, target_data)
gain(Einisial, Enew3)

0.2985203537604644