In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/zakkiya/dataminingProject/master/drug200%20(1).csv')
df

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [3]:
df.head()

   Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [4]:
Sex = pd.get_dummies(df.Sex)
df = df.drop(columns = ['Sex'])
df[["F", "M"]] = Sex

In [5]:
df

     Age      BP Cholesterol  Na_to_K   Drug  F  M
0     23    HIGH        HIGH   25.355  DrugY  1  0
1     47     LOW        HIGH   13.093  drugC  0  1
2     47     LOW        HIGH   10.114  drugC  0  1
3     28  NORMAL        HIGH    7.798  drugX  1  0
4     61     LOW        HIGH   18.043  DrugY  1  0
..   ...     ...         ...      ...    ... .. ..
195   56     LOW        HIGH   11.567  drugC  1  0
196   16     LOW        HIGH   12.006  drugC  0  1
197   52  NORMAL        HIGH    9.894  drugX  0  1
198   23  NORMAL      NORMAL   14.020  drugX  0  1
199   40     LOW      NORMAL   11.349  drugX  1  0

[200 rows x 7 columns]

In [6]:
BP = pd.get_dummies(df.BP)
df = df.drop(columns = ['BP'])
df[["HIGH_BP", "LOW_BP", "NORMAL_BP"]] = BP

In [7]:
df

     Age Cholesterol  Na_to_K   Drug  F  M  HIGH_BP  LOW_BP  NORMAL_BP
0     23        HIGH   25.355  DrugY  1  0        1       0          0
1     47        HIGH   13.093  drugC  0  1        0       1          0
2     47        HIGH   10.114  drugC  0  1        0       1          0
3     28        HIGH    7.798  drugX  1  0        0       0          1
4     61        HIGH   18.043  DrugY  1  0        0       1          0
..   ...         ...      ...    ... .. ..      ...     ...        ...
195   56        HIGH   11.567  drugC  1  0        0       1          0
196   16        HIGH   12.006  drugC  0  1        0       1          0
197   52        HIGH    9.894  drugX  0  1        0       0          1
198   23      NORMAL   14.020  drugX  0  1        0       0          1
199   40      NORMAL   11.349  drugX  1  0        0       1          0

[200 rows x 9 columns]

In [8]:
Cholesterol = pd.get_dummies(df.Cholesterol)
df = df.drop(columns = ['Cholesterol'])
df[["HIGH_Cl", "NORMAL_CL"]] = Cholesterol

In [9]:
df

     Age  Na_to_K   Drug  F  M  HIGH_BP  LOW_BP  NORMAL_BP  HIGH_Cl  NORMAL_CL
0     23   25.355  DrugY  1  0        1       0          0        1          0
1     47   13.093  drugC  0  1        0       1          0        1          0
2     47   10.114  drugC  0  1        0       1          0        1          0
3     28    7.798  drugX  1  0        0       0          1        1          0
4     61   18.043  DrugY  1  0        0       1          0        1          0
..   ...      ...    ... .. ..      ...     ...        ...      ...        ...
195   56   11.567  drugC  1  0        0       1          0        1          0
196   16   12.006  drugC  0  1        0       1          0        1          0
197   52    9.894  drugX  0  1        0       0          1        1          0
198   23   14.020  drugX  0  1        0       0          1        0          1
199   40   11.349  drugX  1  0        0       1          0        0          1

[200 rows x 10 columns]

In [10]:
X = df.drop(columns = ['Drug', 'Age','Na_to_K'])
y = df.Drug
X

     F  M  HIGH_BP  LOW_BP  NORMAL_BP  HIGH_Cl  NORMAL_CL
0    1  0        1       0          0        1          0
1    0  1        0       1          0        1          0
2    0  1        0       1          0        1          0
3    1  0        0       0          1        1          0
4    1  0        0       1          0        1          0
..  .. ..      ...     ...        ...      ...        ...
195  1  0        0       1          0        1          0
196  0  1        0       1          0        1          0
197  0  1        0       0          1        1          0
198  0  1        0       0          1        0          1
199  1  0        0       1          0        0          1

[200 rows x 7 columns]

In [11]:
df.groupby('Drug')['Drug'].count()

Drug
DrugY    91
drugA    23
drugB    16
drugC    16
drugX    54
Name: Drug, dtype: int64



*   List item
*   List item

In [12]:
L = df[["Age","Na_to_K"]] 
L

     Age  Na_to_K
0     23   25.355
1     47   13.093
2     47   10.114
3     28    7.798
4     61   18.043
..   ...      ...
195   56   11.567
196   16   12.006
197   52    9.894
198   23   14.020
199   40   11.349

[200 rows x 2 columns]

In [13]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled= scaler.fit_transform(L)
features_names = L.columns.copy()
scaled_features = pd.DataFrame(scaled, columns=features_names)
scaled_features.head(10)

        Age   Na_to_K
0  0.135593  0.596848
1  0.542373  0.213397
2  0.542373  0.120239
3  0.220339  0.047814
4  0.779661  0.368191
5  0.118644  0.073113
6  0.576271  0.312903
7  0.440678  0.149103
8  0.762712  0.278379
9  0.474576  0.409625

In [14]:
scaler = pd.concat([scaled_features,X], axis=1)
scaler

          Age   Na_to_K  F  M  HIGH_BP  LOW_BP  NORMAL_BP  HIGH_Cl  NORMAL_CL
0    0.135593  0.596848  1  0        1       0          0        1          0
1    0.542373  0.213397  0  1        0       1          0        1          0
2    0.542373  0.120239  0  1        0       1          0        1          0
3    0.220339  0.047814  1  0        0       0          1        1          0
4    0.779661  0.368191  1  0        0       1          0        1          0
..        ...       ... .. ..      ...     ...        ...      ...        ...
195  0.694915  0.165676  1  0        0       1          0        1          0
196  0.016949  0.179405  0  1        0       1          0        1          0
197  0.627119  0.113359  0  1        0       0          1        1          0
198  0.135593  0.242385  0  1        0       0          1        0          1
199  0.423729  0.158859  1  0        0       1          0        0          1

[200 rows x 9 columns]

In [15]:
import joblib
filename = "drugsave"
joblib.dump(scaler, filename)

['drugsave']

In [16]:
cls = df['Drug'].values

In [17]:
from sklearn import preprocessing
y = preprocessing.LabelEncoder()
cls_encoder = y.fit_transform(cls)
cls_encoder

array([0, 3, 3, 4, 0, 4, 0, 3, 0, 0, 3, 0, 0, 0, 4, 0, 4, 1, 3, 0, 0, 0,
       0, 0, 0, 0, 0, 4, 0, 0, 4, 2, 4, 0, 4, 4, 1, 4, 4, 4, 0, 2, 0, 4,
       4, 4, 1, 3, 0, 0, 0, 4, 0, 0, 2, 3, 2, 0, 4, 0, 0, 1, 0, 4, 2, 0,
       1, 4, 0, 0, 2, 0, 4, 0, 0, 0, 1, 0, 1, 4, 2, 4, 3, 1, 3, 2, 4, 0,
       0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 1, 1, 3, 4, 0, 4, 4, 0, 2, 0,
       1, 4, 4, 4, 4, 0, 4, 4, 1, 0, 0, 0, 0, 0, 2, 0, 0, 4, 0, 4, 0, 0,
       4, 0, 0, 4, 2, 1, 2, 4, 1, 0, 2, 0, 1, 4, 4, 1, 4, 3, 1, 2, 4, 4,
       0, 3, 1, 0, 3, 4, 4, 2, 4, 0, 0, 0, 0, 4, 0, 1, 4, 4, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 4, 4, 0, 0, 0, 2, 1, 0, 0, 0, 1, 0, 3, 0, 3, 3, 4,
       4, 4])

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(scaler, cls_encoder, test_size=0.3, random_state=1)

knn

In [19]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

# my_param_grid = {'n_neighbors':[2,3,5,7], 'weights': ['distance', 'uniform']}
# GridSearchCV(estimator=KNeighborsClassifier(), param_grid=my_param_grid, refit=True, verbose=3, cv=3)
# knn = GridSearchCV(KNeighborsClassifier(), param_grid=my_param_grid, refit=True, verbose=3, cv=3)

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [20]:
#save model knn
filenameModelKnnNorm = 'modelKnnNorm.pkl'
joblib.dump(knn, filenameModelKnnNorm)

['modelKnnNorm.pkl']

In [21]:
print("Score data latih = ",knn.score(X_train, y_train))
print("Score data test = ",knn.score(X_test,y_test))
akurasi = knn.score(X_test, y_test) * 100
print("Hasil akurasi = ", round(akurasi,2), "%")
prediksi_knn = knn.predict([[0.135593,0.596848,	1,	0,	1,	0,	0,	1,	0]])
print("Hasil prediksi = ", prediksi_knn[0])

Score data latih =  1.0
Score data test =  0.8
Hasil akurasi =  80.0 %
Hasil prediksi =  0

naive bayes

In [22]:
# training the model on training set
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [23]:
filenameModelGau = 'modelGau.pkl'
joblib.dump(gnb, filenameModelGau)

['modelGau.pkl']

In [24]:
print("Score data latih = ",gnb.score(X_train, y_train))
print("Score data test = ",gnb.score(X_test,y_test))
akurasi = gnb.score(X_test, y_test) * 100
print("Hasil akurasi = ", round(akurasi,2),"%")
prediksi_gnb = gnb.predict([[0.135593,0.596848,	1,	0,	1,	0,	0,	1,	0]])
print("Hasil prediksi = ", prediksi_gnb[0])

Score data latih =  0.7142857142857143
Score data test =  0.65
Hasil akurasi =  65.0 %
Hasil prediksi =  1

random forest

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

# X, y = make_classification(n_samples=1000, n_features=4, n_informative=2, n_redundant=0, random_state=0, shuffle=False)
rf = RandomForestClassifier(max_depth=2, random_state=0)
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=2, random_state=0)

In [26]:
print("Score data latih = ",rf.score(X_train, y_train))
print("Score data test = ",rf.score(X_test,y_test))
akurasi = rf.score(X_test, y_test) * 100
print("Hasil akurasi = ", round(akurasi,2),"%")
prediksi_rf = rf.predict([[0.135593,0.596848,	1,	0,	1,	0,	0,	1,	0]])
print("Hasil prediksi = ", prediksi_rf[0])

Score data latih =  0.8428571428571429
Score data test =  0.8333333333333334
Hasil akurasi =  83.33 %
Hasil prediksi =  0

decision tree

In [27]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [28]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [29]:
print("Score data latih = ",dt.score(X_train, y_train))
print("Score data test = ",dt.score(X_test,y_test))
akurasi = dt.score(X_test, y_test) * 100
print("Hasil akurasi = ", round(akurasi,2),"%")
prediksi_dt = dt.predict([[0.135593,0.596848,	1,	0,	1,	0,	0,	1,	0]])
print("Hasil prediksi = ", prediksi_dt[0])

Score data latih =  1.0
Score data test =  0.9833333333333333
Hasil akurasi =  98.33 %
Hasil prediksi =  0